// Build the Mezze style-layer bundle for Claude Design.
//
// This repo is an Odoo addon, not a JS package, so the skill's converter cannot
// run: the components are Owl and are resolved by Odoo's asset bundler. What IS
// portable is the style layer, and this script assembles it deterministically
// from the addon's own stylesheets. Nothing here is re-authored.
import fs from 'node:fs';
import path from 'node:path';

const ADDON = 'addons/mezze_bridge';
const OUT = 'ds-bundle';
const rd = p => fs.readFileSync(path.join(ADDON, p), 'utf8');
const wr = (p, s) => { fs.mkdirSync(path.dirname(path.join(OUT, p)), {recursive:true}); fs.writeFileSync(path.join(OUT, p), s); };

fs.rmSync(OUT, {recursive:true, force:true});

// ---- fonts: the vendored OFL faces, copied verbatim -------------------------
const fontDir = path.join(ADDON, 'static/fonts');
const fonts = fs.readdirSync(fontDir).filter(f => f.endsWith('.woff2'));
fs.mkdirSync(path.join(OUT, 'fonts'), {recursive:true});
for (const f of fonts) fs.copyFileSync(path.join(fontDir, f), path.join(OUT, 'fonts', f));

// ---- foundation: @font-face + geometry/type tokens --------------------------
// Only the asset URLs change. Odoo serves them from an addon path that does not
// exist here, so they are rewritten to sit beside the bundle.
const foundation = rd('static/design/foundation.css')
  .replaceAll('/mezze_bridge/static/fonts/', '../fonts/');
if (foundation.includes('/mezze_bridge/')) throw new Error('unrewritten addon URL in foundation.css');
wr('tokens/foundation.css', foundation);

// ---- palette: 12 themes x 9 accents, generated by static/gen_design.py ------
const palette = rd('static/mezze-design.css');
wr('tokens/palette.css', palette);
wr('tokens/MEZZE_DESIGN_TOKENS.json', rd('docs/design-handoff/ui-design/MEZZE_DESIGN_TOKENS.json'));

// ---- default theme on a bare :root -----------------------------------------
// Every token above is scoped to :root[data-appearance="mezze"], because in the
// product an inline pre-paint resolver stamps that attribute. A design rendered
// here starts with a bare <html>, so without this the whole system falls back to
// browser defaults. The block is EXTRACTED from the generated palette rather
// than hand-copied, so gen_design.py stays the single source of these values.
const grab = (sel) => {
  const i = palette.indexOf(sel);
  if (i < 0) throw new Error('missing block: ' + sel);
  const a = palette.indexOf('{', i), b = palette.indexOf('}', a);
  return palette.slice(a + 1, b).trim();
};
const bridge = grab(':root[data-appearance="mezze"]{');
const classic = grab(':root[data-appearance="mezze"][data-mz-theme="classic"]{');
wr('tokens/root-default.css', `/* GENERATED by .design-sync/build.mjs — do not hand-edit.
   The product stamps data-appearance="mezze" and data-mz-theme on <html> before
   first paint. A rendered design has none of that, so the default theme (classic,
   light) is re-emitted here for a bare :root. Values are extracted from
   tokens/palette.css at build time; gen_design.py remains their only source.
   Setting the attributes still works and still wins, so theme switching is
   unaffected — see README. */
:root{
${classic}
}
:root{
${bridge}
}
`);

// ---- component vocabulary ---------------------------------------------------
// The staff design layer only. The kiosk sheets are a separate surface and
// cashier.css is Register-screen furniture rather than reusable vocabulary.
const parts = [
  'static/design/components.css',
  'static/design/category-nav.css',
  'static/design/order-panel.css',
  'static/design/product-browser.css',
  'static/design/product-config.css',
  'static/src/shell/rail.css',
];
const bundle = parts.map(p => `/* ===== ${p} ===== */\n` + rd(p)).join('\n\n');
if (bundle.includes('url(')) throw new Error('component CSS gained an asset URL; rewrite it');
wr('_ds_bundle.css', bundle);

// ---- the entry ---------------------------------------------------------------
// Rendered designs receive ONLY this file's transitive @import closure, so
// everything the system needs has to be reachable from here.
wr('styles.css', `/* Mezze POS — design system entry.
   Order matters: fonts and geometry, then the colour registry, then the default
   theme for a bare root, then the component vocabulary. */
@import "./tokens/foundation.css";
@import "./tokens/palette.css";
@import "./tokens/root-default.css";
@import "./_ds_bundle.css";
`);

const count = (d) => fs.readdirSync(path.join(OUT, d)).length;
console.log(JSON.stringify({
  fonts: count('fonts'),
  tokens: count('tokens'),
  bundleKB: Math.round(Buffer.byteLength(bundle)/1024),
  paletteKB: Math.round(Buffer.byteLength(palette)/1024),
}, null, 1));
